version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"   # MQTT protocol port
      - "9001:9001"   # MQTT over WebSockets
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

  mariadb:
      image: mariadb:latest # replace with actual image if it's available
      container_name: mariadb
      environment:
        MYSQL_ROOT_PASSWORD: rootpassword  # Root user password
        MYSQL_DATABASE: mydatabase         # Database to be created
        MYSQL_USER: myuser                 # Additional user to be created
        MYSQL_PASSWORD: mypassword         # Password for the additional user
        MARIA_DB_USER: admin
        MARIA_DB_PASSWORD: admin_password
      ports:
        - "3306:3306" 
      volumes:
        - ./mariadb/data:/data/db
        - ../sql:/docker-entrypoint-initdb.d  # Mount your SQL script
      restart: unless-stopped

  kekbosrv:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: kekbosrv
    ports:
      - "8000:8000"   # FastAPI app port
    depends_on:
      - mosquitto  # Ensure mosquitto starts first
    restart: unless-stopped